from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import ListingViewSet,BookingViewSet

# create an instance f the router
router = DefaultRouter()

# register the Viewset with a URl prefix
router.register(r'listings', ListingViewSet, basename ='listing')
router.register(r'bookings', BookingViewSet, basename = 'booking')

# url patterns now includes all the URLS generated by the router
urlpatterns = [
    path('api/v1/', include(router.urls)),
    
]